# Generated by Django 5.2.7 on 2025-11-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='images/')),
                ('author', models.CharField(default='Guest', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(default='I am a guest of ISMT')),
                ('published_date', models.DateField()),
            ],
        ),
    ]
