# Generated by Django 5.2.7 on 2025-11-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relation', '0003_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='Relation.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
    ]
